interface Event {
  id: number;
  year: number;
  month: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;
  day: number;
  eventDate: string;
  eventType: 'public' | 'custom';
  title: string;
  content: string;
  createdAt: string;
}

const events: Event[] = [
  {
    id: 1,
    year: 2022,
    month: 0,
    day: 5,
    eventDate: '2022-01-05',
    eventType: 'public',
    title: "New Year's Gala",
    content: 'Celebrating the new year with a grand gala.',
    createdAt: '2022-01-01',
  },
  {
    id: 2,
    year: 2022,
    month: 0,
    day: 12,
    eventDate: '2022-01-12',
    eventType: 'custom',
    title: 'Winter Workshop',
    content: 'A workshop focusing on creative winter crafts.',
    createdAt: '2021-12-15',
  },
  {
    id: 3,
    year: 2022,
    month: 0,
    day: 20,
    eventDate: '2022-01-20',
    eventType: 'public',
    title: 'Local Music Festival',
    content: 'Showcasing local bands and musicians.',
    createdAt: '2021-12-20',
  },
  {
    id: 4,
    year: 2022,
    month: 0,
    day: 28,
    eventDate: '2022-01-28',
    eventType: 'custom',
    title: 'Community Game Night',
    content: 'A fun night of games and community bonding.',
    createdAt: '2022-01-10',
  },
  {
    id: 5,
    year: 2022,
    month: 1,
    day: 4,
    eventDate: '2022-02-04',
    eventType: 'public',
    title: 'Groundhog Day Gathering',
    content: 'A community event to celebrate Groundhog Day.',
    createdAt: '2022-01-28',
  },
  {
    id: 6,
    year: 2022,
    month: 1,
    day: 14,
    eventDate: '2022-02-14',
    eventType: 'custom',
    title: "Valentine's Day Social",
    content: 'A special event for couples and friends to celebrate love.',
    createdAt: '2022-02-07',
  },
  {
    id: 7,
    year: 2022,
    month: 1,
    day: 22,
    eventDate: '2022-02-22',
    eventType: 'public',
    title: 'Winter Photo Expo',
    content: 'Exhibition showcasing stunning winter photography.',
    createdAt: '2022-02-15',
  },
  {
    id: 8,
    year: 2022,
    month: 1,
    day: 28,
    eventDate: '2022-02-28',
    eventType: 'custom',
    title: 'Leap Year Celebration',
    content: 'A fun event to celebrate the leap year.',
    createdAt: '2022-02-21',
  },

  {
    id: 9,
    year: 2022,
    month: 2,
    day: 8,
    eventDate: '2022-03-08',
    eventType: 'public',
    title: "International Women's Day",
    content: 'Celebrating the achievements of women around the world.',
    createdAt: '2022-03-01',
  },
  {
    id: 10,
    year: 2022,
    month: 2,
    day: 17,
    eventDate: '2022-03-17',
    eventType: 'custom',
    title: "St. Patrick's Day Parade",
    content: "Join the festive green parade on St. Patrick's Day.",
    createdAt: '2022-03-10',
  },
  {
    id: 11,
    year: 2022,
    month: 2,
    day: 21,
    eventDate: '2022-03-21',
    eventType: 'public',
    title: 'Spring Equinox Celebration',
    content: 'Welcoming the first day of spring with open arms.',
    createdAt: '2022-03-14',
  },
  {
    id: 12,
    year: 2022,
    month: 2,
    day: 31,
    eventDate: '2022-03-31',
    eventType: 'custom',
    title: 'End of Month Concert',
    content: 'An evening of live music to bid farewell to March.',
    createdAt: '2022-03-24',
  },
  {
    id: 13,
    year: 2022,
    month: 3, // April
    day: 1,
    eventDate: '2022-04-01',
    eventType: 'public',
    title: "April Fool's Day Comedy Show",
    content: 'A night of laughter and pranks.',
    createdAt: '2022-03-25',
  },
  {
    id: 14,
    year: 2022,
    month: 3,
    day: 15,
    eventDate: '2022-04-15',
    eventType: 'custom',
    title: 'Tax Day Financial Workshop',
    content: 'Get tips and advice for managing your taxes.',
    createdAt: '2022-04-08',
  },
  {
    id: 15,
    year: 2022,
    month: 3,
    day: 22,
    eventDate: '2022-04-22',
    eventType: 'public',
    title: 'Earth Day Cleanup',
    content: 'Join us in a community cleanup to honor Earth Day.',
    createdAt: '2022-04-15',
  },
  {
    id: 16,
    year: 2022,
    month: 3,
    day: 30,
    eventDate: '2022-04-30',
    eventType: 'custom',
    title: 'Spring Art Fair',
    content: 'Explore the works of local artists at our annual fair.',
    createdAt: '2022-04-23',
  },
  {
    id: 17,
    year: 2022,
    month: 4,
    day: 5,
    eventDate: '2022-05-05',
    eventType: 'public',
    title: 'Cinco de Mayo Festival',
    content: 'A vibrant celebration of Mexican culture and heritage.',
    createdAt: '2022-04-28',
  },
  {
    id: 18,
    year: 2022,
    month: 4,
    day: 14,
    eventDate: '2022-05-14',
    eventType: 'custom',
    title: 'Community Health Fair',
    content: 'Free health screenings and wellness activities.',
    createdAt: '2022-05-07',
  },
  {
    id: 19,
    year: 2022,
    month: 4,
    day: 21,
    eventDate: '2022-05-21',
    eventType: 'public',
    title: 'Armed Forces Day Parade',
    content: 'Honoring our military service members with a grand parade.',
    createdAt: '2022-05-14',
  },
  {
    id: 20,
    year: 2022,
    month: 4,
    day: 30,
    eventDate: '2022-05-30',
    eventType: 'custom',
    title: 'Memorial Day Remembrance',
    content: 'A solemn event to remember and honor fallen soldiers.',
    createdAt: '2022-05-23',
  },
  {
    id: 21,
    year: 2022,
    month: 5,
    day: 5,
    eventDate: '2022-06-05',
    eventType: 'public',
    title: 'World Environment Day',
    content: 'Activities and workshops focused on environmental protection.',
    createdAt: '2022-05-29',
  },
  {
    id: 22,
    year: 2022,
    month: 5,
    day: 14,
    eventDate: '2022-06-14',
    eventType: 'custom',
    title: 'Flag Day Celebration',
    content: 'A day of patriotism and pride in our nation.',
    createdAt: '2022-06-07',
  },
  {
    id: 23,
    year: 2022,
    month: 5,
    day: 21,
    eventDate: '2022-06-21',
    eventType: 'public',
    title: 'Summer Solstice Party',
    content: 'Join us in celebrating the longest day of the year.',
    createdAt: '2022-06-14',
  },
  {
    id: 24,
    year: 2022,
    month: 5,
    day: 30,
    eventDate: '2022-06-30',
    eventType: 'custom',
    title: 'End of Month Jazz Night',
    content: 'Relax with an evening of smooth jazz and fine dining.',
    createdAt: '2022-06-23',
  },
  {
    id: 25,
    year: 2023,
    month: 10, // November
    day: 5,
    eventDate: '2023-11-05',
    eventType: 'public',
    title: 'Autumn Art Exhibition',
    content: 'Showcase of local artists celebrating the colors of autumn.',
    createdAt: '2023-10-29',
  },
  {
    id: 26,
    year: 2023,
    month: 10,
    day: 11,
    eventDate: '2023-11-11',
    eventType: 'custom',
    title: 'Veterans Day Parade',
    content: 'A parade to honor and thank our military veterans.',
    createdAt: '2023-11-04',
  },
  {
    id: 27,
    year: 2023,
    month: 10,
    day: 23,
    eventDate: '2023-11-23',
    eventType: 'public',
    title: 'Thanksgiving Community Feast',
    content: 'Join us for a community gathering and Thanksgiving feast.',
    createdAt: '2023-11-16',
  },
  {
    id: 28,
    year: 2023,
    month: 10,
    day: 30,
    eventDate: '2023-11-30',
    eventType: 'custom',
    title: 'End of Month Film Screening',
    content: 'A special screening of an acclaimed film to close out the month.',
    createdAt: '2023-11-23',
  },
  {
    id: 29,
    year: 2023,
    month: 11,
    day: 5,
    eventDate: '2023-12-05',
    eventType: 'public',
    title: 'Winter Wonderland Festival',
    content: 'A festive celebration with lights, music, and holiday cheer.',
    createdAt: '2023-11-28',
  },
  {
    id: 30,
    year: 2023,
    month: 11,
    day: 15,
    eventDate: '2023-12-15',
    eventType: 'custom',
    title: 'Holiday Market',
    content: 'An outdoor market featuring unique gifts and seasonal treats.',
    createdAt: '2023-12-08',
  },
  {
    id: 31,
    year: 2023,
    month: 11,
    day: 24,
    eventDate: '2023-12-24',
    eventType: 'public',
    title: 'Christmas Eve Celebration',
    content: 'A magical evening of music, stories, and community spirit.',
    createdAt: '2023-12-17',
  },
  {
    id: 32,
    year: 2023,
    month: 11,
    day: 31,
    eventDate: '2023-12-31',
    eventType: 'custom',
    title: "New Year's Eve Countdown",
    content: 'Ring in the New Year with fireworks and festivities.',
    createdAt: '2023-12-24',
  },
  {
    id: 33,
    year: 2024,
    month: 0,
    day: 1,
    eventDate: '2024-01-01',
    eventType: 'public',
    title: "New Year's Day Celebration",
    content: 'Start the new year with joy and celebration at our annual event.',
    createdAt: '2023-12-25',
  },
  {
    id: 34,
    year: 2024,
    month: 0,
    day: 15,
    eventDate: '2024-01-15',
    eventType: 'custom',
    title: 'Mid-January Wellness Workshop',
    content: 'A workshop focused on health and wellness for the new year.',
    createdAt: '2024-01-08',
  },
  {
    id: 35,
    year: 2024,
    month: 0,
    day: 22,
    eventDate: '2024-01-22',
    eventType: 'public',
    title: 'Community Service Day',
    content:
      'Join us in giving back to the community with various service projects.',
    createdAt: '2024-01-15',
  },
  {
    id: 36,
    year: 2024,
    month: 0,
    day: 31,
    eventDate: '2024-01-31',
    eventType: 'custom',
    title: 'End of Month Movie Night',
    content: 'A cozy movie night to wrap up the first month of the year.',
    createdAt: '2024-01-24',
  },
];

export default events;
